version: '3.8'

services:
  api:    
    # image: one-backend
    # container_name: nest_blog
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - '3001:3000'
    command: npm run start:dev
    
    depends_on:
      - db
      #- redis
    volumes:
      - .:/usr/src/blog
      - /usr/src/blog/node_modules
    networks:
      - blog
  db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME:
      MONGO_INITDB_ROOT_PASSWORD:
    ports:
        - '27018:27017'
    volumes:
      - mongodb:/data/db
    networks:
      - blog
        
  # Mail Trap for Development
  # mailhog:
  #     image: 'mailhog/mailhog:latest'
  #     ports:
  #         - '${FORWARD_MAILHOG_PORT:-1026}:1025'
  #         - '${FORWARD_MAILHOG_DASHBOARD_PORT:-8026}:8025'
  #     networks:
  #         - one

  # redis:
  #     image: "redis:alpine"
  #     command: redis-server --requirepass sOmE_sEcUrE_pAsS
  #     ports:
  #         - "6380:6379"
  #     volumes:
  #         - 'redis:/var/lib/redis'
  #     environment:
  #         - REDIS_REPLICATION_MODE=master
  
  #     networks:
  #         - one

networks:
  blog:
    driver: bridge

volumes:
  mongodb:
    driver: local
  redis:
    driver: local

  